# Generated by Django 2.1.2 on 2018-10-25 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_profile_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='playlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='playlist_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='music.Playlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
