# Generated by Django 2.1.2 on 2018-10-30 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0004_auto_20181029_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='title',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='url',
            field=models.TextField(default='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
