# Generated by Django 2.1.2 on 2018-10-30 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20181030_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='playlist_id',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
