# Generated by Django 2.1.2 on 2018-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20181030_2237'),
        ('music', '0005_auto_20181030_2326'),
    ]

    operations = [
    ]
